sites:
  example:
    name: 'Example.com'
    url: 'https://example.com/factmc'
    
clearlag:
  enabled: true
  hide-messages: false
  interval: 900 # 15 minutes
  warnings:
  - 780 # 120 seconds left
  - 840 # 60 seconds left
  - 870 # 30 seconds left
  - 890 # 10 seconds left
  remove-types:
  - AREA_EFFECT_CLOUD
  - ARROW
  - DRAGON_FIREBALL
  - DROPPED_ITEM
  - EGG
  - ENDER_PEARL
  - ENDER_SIGNAL
  - EXPERIENCE_ORB
  - FALLING_BLOCK
  - FIREBALL
  - FIREWORK
  - FISHING_HOOK
  - PRIMED_TNT
  - SHULKER_BULLET
  - SMALL_FIREBALL
  - SNOWBALL
  - SPECTRAL_ARROW
  - SPLASH_POTION
  - THROWN_EXP_BOTTLE
  - WITHER_SKULL

bossbar:
  rate: 0.3
  title:
  - '&6&lFACT Minecraft Network'
  - '&2&lF&6&lACT Minecraft Network'
  - '&2&lFA&6&lCT Minecraft Network'
  - '&2&lFAC&6&lT Minecraft Network'
  - '&2&lFACT&6&l Minecraft Network'
  - '&2&lFACT M&6&linecraft Network'
  - '&2&lFACT Mi&6&lnecraft Network'
  - '&2&lFACT Min&6&lecraft Network'
  - '&2&lFACT Mine&6&lcraft Network'
  - '&2&lFACT Minec&6&lraft Network'
  - '&2&lFACT Minecr&6&laft Network'
  - '&2&lFACT Minecra&6&lft Network'
  - '&2&lFACT Minecraf&6&lt Network'
  - '&2&lFACT Minecraft&6&l Network'
  - '&2&lFACT Minecraft N&6&letwork'
  - '&2&lFACT Minecraft Ne&6&ltwork'
  - '&2&lFACT Minecraft Net&6&lwork'
  - '&2&lFACT Minecraft Netw&6&lork'
  - '&2&lFACT Minecraft Netwo&6&lrk'
  - '&2&lFACT Minecraft Networ&6&lk'
  - '&2&lFACT Minecraft Network'
  - '&6&lF&2&lACT Minecraft Network'
  - '&6&lFA&2&lCT Minecraft Network'
  - '&6&lFAC&2&lT Minecraft Network'
  - '&6&lFACT&2&l Minecraft Network'
  - '&6&lFACT M&2&linecraft Network'
  - '&6&lFACT Mi&2&lnecraft Network'
  - '&6&lFACT Min&2&lecraft Network'
  - '&6&lFACT Mine&2&lcraft Network'
  - '&6&lFACT Minec&2&lraft Network'
  - '&6&lFACT Minecr&2&laft Network'
  - '&6&lFACT Minecra&2&lft Network'
  - '&6&lFACT Minecraf&2&lt Network'
  - '&6&lFACT Minecraft&2&l Network'
  - '&6&lFACT Minecraft N&2&letwork'
  - '&6&lFACT Minecraft Ne&2&ltwork'
  - '&6&lFACT Minecraft Net&2&lwork'
  - '&6&lFACT Minecraft Netw&2&lork'
  - '&6&lFACT Minecraft Netwo&2&lrk'
  - '&6&lFACT Minecraft Networ&2&lk'
  color:
  - 'PURPLE'
  style:
  - 'SOLID'
  
playtime-ranks:
  vip:
    playtime: 172800 # 48 hours
    prerequisite: default
  mvp:
    playtime: 604800 # 168 Hours (7 days)
    prerequisite: vip