name: FactBukkit
main: net.factmc.FactBukkit.Main
version: 1.10.1
author: TrollyLoki

depend: [LuckPerms, FactCore]
softdepend: [Vault, SuperVanish, ClearLag, GriefPrevention, PlotSquared, WorldGuard]

api-version: 1.14

commands:
  points:
  rtag-update:
    permission: factbukkit.update
  cancelclear:
  edit:
  stats:
  trails: