name: FactBasic
main: net.factmc.FactBasic.Main
version: 1.9
author: TrollyLoki

depend: [LuckPerms, FactCore]
softdepend: [SuperVanish, GriefPrevention, ClearLag]

api-version: 1.14

commands:
  rtag-update:
    permission: factbasic.update
  cancelclear: