name: ${project.artifactId}
main: ${project.groupId}.Main
version: ${project.version}
author: TrollyLoki

depend: [LuckPerms, FactCore]
softdepend: [Vault, SuperVanish, ClearLag, GriefPrevention, PlotSquared, WorldEdit, WorldGuard, ViaVersion]

api-version: 1.16

commands:
  points:
  rtag-update:
    permission: factbukkit.update
  cancelclear:
  edit:
  stats:
  vote:
  servers:
  clearlag: