name: FactBasic
main: net.factmc.FactBasic.Main
version: 1.8
author: TrollyLoki

depend: [BungeePerms, FactCore]
softdepend: [SuperVanish, GriefPrevention]

api-version: 1.14

commands:
  rtag-update:
    permission: factbasic.update