name: FactBasic
main: net.factmc.FactBasic.Main
version: 1.8
author: TrollyLoki

depend: [BungeePerms, FactCore]
softdepend: [SuperVanish]

api-version: 1.13

commands:
  rtag-update:
    permission: factbasic.update