name: FactBasic
main: net.factmc.FactBasic.Main
version: 1.9.1
author: TrollyLoki

depend: [LuckPerms, FactCore]
softdepend: [SuperVanish, ClearLag, GriefPrevention, PlotSquared, WorldGuard]

api-version: 1.14

commands:
  rtag-update:
    permission: factbasic.update
  cancelclear:
  edit: